### PR TITLE
Update to Blazor 0.9.0

### PR DESCRIPTION
**Pull request by kswoll**
* `IJSRuntime` must be injected, so changed all usages of `JSRuntime.Current`
* Updated the relevant framework version and package references
* Stopped using the logging library and changed to `Console.WriteLine` -- not sure the library was adding anything useful and was just another dependency that has to constantly be upgraded.

### CODE REVIEW

**Comment by kswoll** [comment]
Seems the CI server is expecting .net core 2.1 instead of 3.0 preview.  Not sure what to do about that.

**Comment by seriouz** [comment]
Update the [global.json](https://github.com/BlazorExtensions/SignalR/blob/master/global.json) file to the correct sdk!

**Comment by kswoll** [comment]
Ah, thanks, let me try that! 🙂

**Comment by andrecarlucci** [comment]
Any updates on this?

**Comment by kswoll** [comment]
@andrecarlucci I don't know how to fix the build, unfortunately.  Not sure what value it's expecting for the SDK version.  I tried a few values, none of them worked.

**Comment by jwikberg** [comment]
@kswoll The preview SDK is not installed in the hosted agent images.
It has to be installed by adding a [.NET Core tool installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) task to the pipeline.

**Comment by kswoll** [comment]
Thanks @jwikberg!  Though seeing as this repo (nor the agent) is owned by me, presumably the repo owner will have to take care of this.

**Comment by jwikberg** [comment]
> Thanks @jwikberg! Though seeing as neither this repo (nor the agent) is owned by me, presumably the repo owner will have to take care of this.

Since the yaml files for the pipelines are in the repo I assume that we just have to update them, I've sent a PR to your branch with the needed changes https://github.com/kswoll/SignalR/pull/1

**Comment by kswoll** [comment]
@jwikberg ohhh, thank you!  Learned something new. :)  Let's see if this works.  🤞

**Comment by kswoll** [comment]
Looks like that worked @jwikberg, nice work! :)

**Comment by kswoll** [comment]
@galvesribeiro any chance we can get this merged?

**Comment by galvesribeiro** [comment]
Thank you all for pushing this! Sorry, I've been so f'ed with work and didn't had time to update all the libraries.

I'll review it early morning when I get tot he office and will let you know.

Thanks!

**Comment by kswoll** [comment]
@galvesribeiro no worries, I know exactly how that can be. :)  Thanks for lookinng into it!

**Comment by endeffects** [comment]
When do u release the changes as preview package?

**Comment by galvesribeiro** [comment]
Thanks @kswoll a lot for your efforts!

This PR's content was merged with #26

**Pull request closed without merging**
