### PR TITLE
Upgrade to Blazor 0.8.0 preview [WiP]

### PR DESCRIPTION
**Pull request by KrzysFR**
I'm trying to upgrade this project to the new Blazor 0.8.0 preview.

I'm following the instructions [from here](https://blogs.msdn.microsoft.com/webdev/2019/02/05/blazor-0-8-0-experimental-release-now-available/), and I got it to build and start, but now I'm getting null reference exceptions inside `Blazor.Extensions.Logging.BrowserConsoleLogger`.

I'm to the point where running the Blazor.Extensions.SignalR.Tests.Server project starts but then immediately fail with the exception below. I think that maybe the `Blazor.Extensions.Logging` must be upgraded first? (the client is using v0.1.8)

Things I had to change:
- Upgrade to .NET Core 3.0 preview 2 (`3.0.100-preview-010184` in `global.json`)
- Update all to Microsoft.AspNetCore.Components.*.dll to `3.0.0-preview-19075-04444`
- Upgrade Blazor.Extensions.SignalR.JS.csproj type to `Microsoft.NET.Sdk.Razor`
- Remove Program.cs from the client, and update the csproj type to `Microsoft.NET.Sdk.Razor`
- Add all the Nuget packages require to have JWT and NewtonsonJson working in the test server.
- Update all the usings in `_ViewImports.cshtml`
- Inherit from `ComponentBase`/`ComponentLayoutBase`
- Change index.html to load `_framework/components.webassembly.js`

I add to install the .NET Core 3.0 preview 2 SDK, and also is running everything from Visual Studio 2019 Preview 2 (does not work in 2017)

I have _no_ idea if everything above is correct, but it got me to building and starting. The rest of the issues seem to be occurring at runtime inside the browser, and I'm have not idea what's going on.

Exception thrown at runtime
```
Microsoft.AspNetCore.Hosting.Internal.WebHost: Critical: Application startup exception

System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazor.Extensions.Logging.BrowserConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>g__Log|0(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>b__1(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggingExtensions.UsingProfileAsKeyRepositoryWithDPAPI(ILogger logger, String fullName)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetFallbackKeyRepositoryEncryptorPair()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory, IDefaultKeyStorageDirectories keyStorageDirectories)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitNoCache(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazor.Extensions.Logging.BrowserConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
```

### CODE REVIEW

**Comment by Duavide** [comment]
Hi! Great work! I think you need to update also the javascript version of SignalR client in package.json to 3.0.0-preview-19075-0444.

**Comment by KrzysFR** [comment]
I updated the JS version to the latest for each package I could find.

I also commented out `services.AddLogging(builder => builder.AddBrowserConsole());` in the Startup of the client, to get rid of the nullref temporarily, 

The server status properly now, but I'm getting a new error in the browser: `InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.` 

I guess there something wrong in the routing on the server side, even though I've added `app.UseStaticFiles();`...

image

The `index.html` file is present in the `Blazor.Extensions.SignalR.Test.Client` assembly, which is referenced by `Blazor.Extensions.SignalR.Test.Server`. I'm thinking that it is not seeing the content files from the linked assembly ?

**Comment by Duavide** [comment]
I found that there was an issiue in the current version of Razor Components. The "content" of Blazor Class Libraries are visible only on "Blazor (ASP.NET Core Hosted)", but not yet on the new version of Razor Components. For details look the issue at [https://github.com/aspnet/AspNetCore/issues/6349](https://github.com/aspnet/AspNetCore/issues/6349). Probably your update works only on blazor web assembly version…

**Comment by KrzysFR** [comment]
I compared a new blazor app produced by the template for 0.8.0 with the current test project, and I noticed that the wwwroot folder is in the _Server_ not the _Client_/_App_. I moved it to the Server assembly, and now index.html and all css are loaded correctly.

Now I'm stuck with `_framework/components.assembly.js` not been loaded (404) which looks like the issue you pointed to?

The new templare use `Host` instead of `WebHost` and does work. I'll try using the same code and see if that changes anything...

**Comment by KrzysFR** [comment]
Ah, that was a typo: I used `_framework/components.webassembly.js` instead of `_framework/components.server.js` :)

Now I'm seeing a blank page, but in the console and network tab, I see some signalr stuff hapening (/negotiate is called and siwtches to websockets).

The last issue is now a JS error (only visible with Edge):
image

Looks like the browser is not loading the JS interop code that is in the assembly `Blazor.Extensions.SignalR.JS` probably for the same reason as above, OR the code in `InitializeSignalR.ts` is not called...

I'm not sure I can do anything more but wait for some things to be fixed upstream in Blazor 0.8.0?

**Comment by IEvangelist** [comment]
Are there any updates on this? I'm curious, do I need this package if I want SignalR to work in Blazor? I have it in my Blazor app now, and I can't figure out if this is the reason why. I'm using the latest bits from Blazor and SignalR.

**Comment by galvesribeiro** [comment]
Hello @KrzysFR! I'm closing this PR as we have merged and published preview4 packages on #26 

Thank you!

**Pull request closed without merging**
