### PR TITLE
Update to Blazor 3.0.0-preview6

### PR DESCRIPTION
**Pull request by theprateik**
- Update global.json to reflect the updated sdk version
- Replace Json.Deserialize by JsonSerializer.Parse in class HubConnection
- Add this. where missing in class HubConnection
- Replace onclick and bind attributes in test razor pages by @onclick and @bind
- Replace @functions by @code in test razor files
- Remove UseSignalR and UseBlazor from test Server Startup class Configure method
- Add UseAuthorization to Startup class
- Comment out AddMessagePackProtocol and uncommented AddJsonProtocol in Startup class
- Comment out AddMessagePackProtocol in ChatComponent class

### CODE REVIEW

**Comment by theprateik** [comment]
#32

**Comment by theprateik** [comment]
Not sure why the check is failing. But there is one issue though, that i noticed.
The test application throws error for Byte Array Argument request when using `MessagePackProtocol`. With `JsonProtocol`, this is not an issue.

**Comment by djinnet** [comment]
I found out that system.text.json don't support some certain datatypes yet as far I have been researched.  I think bytes array is one of these datatypes that system.text.json doesn't fully support without converting the datatype into a string which is json, however, that will fail on the `JsonProtocol`.

I have tried to clone the project and tried to make the same setup except that I am using newtonsoft.json instead of system.text.json because it does support many datatypes.

I am using `JsonConvert.DeserializeObject` instead of `jsonserializer.parse`.

worth mentioning:
Bytes Array argument request is working on `MessagePackProtocol` and `JsonProtocol` on the newtonsoft.json version.

however, I am not sure if it is a bad idea to use newtonsoft.json instead of system.text.json and I hope that that you can give your thoughts on this. What do you think?

**Comment by galvesribeiro** [comment]
Hello! 

Could you please fix the build issue? Its been a while and the build doesn't have the history anymore so I can't check the problem.

**Comment by theprateik** [comment]
There is no issue in building this locally. 
I am not familiar with the DevOps and CI. 
But last time, the reason it failed in DevOps was that the DevOps was not using .NET Core Preview 6 SDK.

**Comment by galvesribeiro** [comment]
You need to change [this](https://github.com/BlazorExtensions/SignalR/blob/master/.vsts-ci.yml#L11) and [this](https://github.com/BlazorExtensions/SignalR/blob/master/.vsts-release.yml#L11) to the appropriate SDK version.

Thanks!

**Comment by theprateik** [comment]
@galvesribeiro, thanks. I will try that and submit soon.

**Comment by theprateik** [comment]
@galvesribeiro, fixed the CI scripts.

**Comment by theprateik** [comment]
> however, I am not sure if it is a bad idea to use newtonsoft.json instead of system.text.json and I hope that that you can give your thoughts on this. What do you think?

@djinnet, it seems .NET Core development team is pushing on `system.text.json`. So, I think this is the way to go.
This could be something that can be discussed though. Maybe an abstraction could be created for json serializer, so that developer could pick a preferred serializer between these two. Again, this could be totally unnecessary since `system.text.json` can become self-sufficient in the future.

**Comment by galvesribeiro** [comment]
I would stick with the new JSON stuff.

The official SignalR client and the Hub uses it by default now, so I wouldn't move the other way around specially that now we're talking about javascript interop in this particular case.

If we ever come to make this "native" in C# only, perhaps we could add the right abstraction...

**Comment by galvesribeiro** [comment]
@theprateik thank YOU so much for the PR! 

Will publish the package soon!

**Pull request merged**
